### ISSUE TITLE
Oculus Shaft incompatibility

### ISSUE THREAD

**Issue by LKD-PIX** [GreateBeyondTheHorizon/Greate#10]
When enabling a shader in Oculus, a gear get's rendered on every shaft block.
Great 0.0.4
1.19.2

![grafik](https://github.com/GreateBeyondTheHorizon/Greate/assets/91191200/cf43eca0-67b1-4c45-843a-d0505d8a8ad6)

![grafik](https://github.com/GreateBeyondTheHorizon/Greate/assets/91191200/206a767e-5cdc-4ae4-b5f7-84c9ed1734cf)

**Comment by LKD-PIX** [comment]
will this fix be backported to 1.19.2 ?

**Comment by Electrolyte220** [comment]
Unfortunately, as I'm the only developer currently working on the project, I simply don't have the time (college yay!) to support 4 different versions (1.19.2 forge/fabric & 1.20.1 forge/fabric), so I'm only sticking to the two 1.20.1 versions.
