### ISSUE TITLE
No Texture for Mechanical Belts

### ISSUE THREAD

**Issue by CilliePaint** [GreateBeyondTheHorizon/Greate#13]
When placing a Mechanical Belt of any type on a Shaft, it appears to have a Missing Texture.

Love the Mod btw, can't wait to see what it becomes!

**Comment by Electrolyte220** [comment]
Hi, thanks for the report.

I'm going to need some more information from you:
1. What version of forge/fabric are you using?
2. What version of Greate are you using?
3. What are the steps to reproduce this?

Thanks.

**Comment by Electrolyte220** [comment]
Closing due to lack of info.
