### ISSUE TITLE
[Bug]: Create Deco Addon recipe incompatibility 

### ISSUE THREAD

**Issue by wsox98** [GreateBeyondTheHorizon/Greate#14]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.2.0

### Greate Version

0.0.9

### What happened?

Greate changes some of the metal sheets into metal plates (for example iron sheet became iron plate). Due to this change, many of the Create Deco recipes cannot be crafted as they require the missing metal sheets. It seems the easiest solution would be to change the Create Deco crafting recipes, so they accept plates.

**Comment by Electrolyte220** [comment]
This seems to be more of a Create Deco problem, as they use their own tags instead of using the forge tags.

**Comment by wsox98** [comment]
I made an easy fix for it by adding the crafting recipes for everything with KubeJ. Its kinda a workaround instead of solving the forge tags issue but if anyone wants it I can share the files.
