### ISSUE TITLE
[Bug]: This Mod is not available on the server.

### ISSUE THREAD

**Issue by aedbia** [GreateBeyondTheHorizon/Greate#16]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.2.19

### Greate Version

0.0.10

### What happened?

Crashes occur when the mod is loaded on the server.

### Log/Crash Report

[crash-2024-01-13_16.24.05-fml.txt](https://github.com/GreateBeyondTheHorizon/Greate/files/13927399/crash-2024-01-13_16.24.05-fml.txt)

**Comment by aedbia** [comment]
[latest.log](https://github.com/GreateBeyondTheHorizon/Greate/files/13927405/latest.log)

This is Logs.

**Comment by lonevox** [comment]
Are you using NeoForge? I believe NeoForge is broken with dedicated servers on 1.20.1. Try regular Forge. If that doesn't work it is probably because we're compiling against NeoForge.

**Comment by aedbia** [comment]
I test Forge and Neoforge, it only work on client,. Maybe some mixins become bad when the server is running and and the client is not running.
