### ISSUE TITLE
[Bug]: JEI doesnt redirect to the following recipe 

### ISSUE THREAD

**Issue by domi-grb** [GreateBeyondTheHorizon/Greate#18]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.2.0

### Greate Version

0.0.11

### What happened?

If you look at the recipe from gtceu and press the U (uses, shortcut to see what you can do) button on the keyboard it just does nothing, but if you look at the recipe from Greate with milling and crushing the next recipe is showing up.

![grafik](https://github.com/GreateBeyondTheHorizon/Greate/assets/95288724/a3525c75-e3db-41f9-9abe-bef2b656e36f)

**Comment by Electrolyte220** [comment]
If using GT version 1.1.0 or greater, you'll have to use Greate 0.0.12 as there was API changes that breaks the JEI plugin.
If using GT before version 1.1.0, you can use Greate versions including and before 0.0.11.
