### ISSUE TITLE
[Bug]: Issues with items on belt

### ISSUE THREAD

**Issue by 4li77l3n00b** [GreateBeyondTheHorizon/Greate#33]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.2.23

### Greate Version

0.0.19

### What happened?

There seems to be some rendering issue with belts and items on belts, and I cannot right-click place anyting on the belt.
![2024-05-10_21 40 49](https://github.com/GreateBeyondTheHorizon/Greate/assets/31160627/c9d06776-a0db-4dbc-ac7c-7c1c47fc5e1b)

https://github.com/GreateBeyondTheHorizon/Greate/assets/31160627/cb547f85-d965-411c-addd-754cbf1979fe

Belt texture not refreshing after breaking in the middle (occurs randomly):
![2024-05-10_22 15 01](https://github.com/GreateBeyondTheHorizon/Greate/assets/31160627/5f5310a0-48da-44eb-8f62-74f4efc9fcdf)

**Comment by Electrolyte220** [comment]
I just released a new version, and your first two issues should be fixed (#32 & #34). Can you check and see if this issue (item rendering) still happens?

**Comment by 4li77l3n00b** [comment]
> I just released a new version, and your first two issues should be fixed (#32 & #34). Can you check and see if this issue (item rendering) still happens?

It's now fixed, thanks for your works.
