### ISSUE TITLE
[Bug]: NullPointerException after dying of electrocution

### ISSUE THREAD

**Issue by 4li77l3n00b** [GreateBeyondTheHorizon/Greate#34]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.2.23

### Greate Version

0.0.19

### What happened?

Actually caused by that belt tier issue so I'm waiting for new release
[crash-2024-05-15_00.19.10-client.txt](https://github.com/GreateBeyondTheHorizon/Greate/files/15311327/crash-2024-05-15_00.19.10-client.txt)

**Comment by Electrolyte220** [comment]
Can you try with [this](https://github.com/GreateBeyondTheHorizon/Greate/actions/runs/9083135687#artifacts) jar and see if you still crash?
You just need to extract the zip after downloading to get the testing jar.
