### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Onitone** [GreateBeyondTheHorizon/Greate#36]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.3.0

### Greate Version

0.0.24

### What happened?

Red Alloy Cable needed to craft LV Steam turbine in turn requires LV tier machine to coat in rubber to make wire into cable. Manually resolved by adding craft tweaker recipe for shapeless paper, string, red alloy wire to make cable.

**Comment by Electrolyte220** [comment]
You shouldn't need any LV machines to make rubber, as the mechanical mixer should have a recipe for raw rubber at ULV. You should be able to pump that out using a greate mechanical pump (you may have to lower the stress consumption for this) and pump it into a spout, where you can coat it.
