### ISSUE TITLE
[Bug]: Failing to join server

### ISSUE THREAD

**Issue by 4li77l3n00b** [GreateBeyondTheHorizon/Greate#38]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

latest

### Greate Version

0.0.25

### What happened?

Server with greate throws exception upon connection preventing me from joining world
Server side log:
`[09:45:54] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: ctrwaz lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class electrolyte.greate.content.processing.recipe.TieredProcessingRecipeSerializer cannot be cast to class com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer (electrolyte.greate.content.processing.recipe.TieredProcessingRecipeSerializer is in module greate@0.0.25 of loader 'TRANSFORMER' @448948ec; com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer is in module create@0.5.1.f of loader 'TRANSFORMER' @448948ec)`
Client:
![image](https://github.com/user-attachments/assets/9355fbef-a2d0-48a6-9ab3-ff99262dbeea)

**Comment by Electrolyte220** [comment]
Can you give me your latest.log?

**Comment by 4li77l3n00b** [comment]
[latest.log](https://github.com/user-attachments/files/16679247/latest.log)
