### ISSUE TITLE
[Bug]: Recipes for the machines don't show up on JEI

### ISSUE THREAD

**Issue by CreepyForest2** [GreateBeyondTheHorizon/Greate#40]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.3.7

### Greate Version

0.0.25-0.0.27

### What happened?

The custom machines added by the mod don't have their recipes show up on JEI, despite them working.
This happens with all versions of GtceuM past 1.4.0, also included.

**Comment by Electrolyte220** [comment]
What version of JEI are you using? I can get the machine recipe & machine recipes to show, on GT 1.4.4 and JEI 15.12.3.53

**Comment by CreepyForest2** [comment]
I figured it out, you need KJS and KJS Create installed.

**Comment by Electrolyte220** [comment]
~~I can get it to work without kubejs/kubejs create installed, can you send a log?~~
I found the issue, fix coming soon.
