### ISSUE TITLE
[Bug]: Game crashes when you throw items on the custom belts

### ISSUE THREAD

**Issue by CreepyForest2** [GreateBeyondTheHorizon/Greate#41]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.3.7

### Greate Version

0.0.28

### What happened?

i threw a wrench on a rubber mech. belt and the game crashed

**Comment by Electrolyte220** [comment]
Please attach the crash report.

**Comment by CreepyForest2** [comment]
it wont let me idk why it says that its been uploaded but it dosnt work
