### ISSUE TITLE
[Bug]: Crash to Desktop when rendering any of the custom belts with the batching backend active

### ISSUE THREAD

**Issue by TheDogOfChaos** [GreateBeyondTheHorizon/Greate#45]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.3.0

### Greate Version

0.0.30

### Create Version

0.5.1.j

### Gregtech Version

1.4.6

### What happened?

Place down any of the custom belts on their applicable shafts.
The game will crash to desktop.
Any attempts to reload the world afterwards with Greate still active will also crash to desktop.

### Log/Crash Report

https://mclo.gs/v988xDB

**Comment by TheDogOfChaos** [comment]
looking at the [overloaded `memSlice` methods](https://github.com/LWJGL/lwjgl3/blob/dea553c7e8136d5981c8713e1502461342487335/modules/lwjgl/core/src/main/java/org/lwjgl/system/MemoryUtil.java#L1313-L1566) of lwjgl, this shit is way too low-level for me to understand much of -- i am at the mercy of you guys

**Comment by Electrolyte220** [comment]
I am unable to reproduce this. Can you try in an instance with only GT, create & greate?

**Comment by TheDogOfChaos** [comment]
update, did what you suggested, but still: https://mclo.gs/leTnEVU

placing belts works fine with the instancing flywheel backend, but i get an immediate CTD when switching to the batching backend with any belts visible and rendering

**Comment by TheDogOfChaos** [comment]
renamed this issue one more time just for ease of backreferencing
